### ISSUE TITLE
[WeChatTicket] 完成后端API

### ISSUE THREAD

**Issue by unbiarirang** [unbiarirang/WeChatTicket#3]
**Describe the problem if you have**
无

**Describe the feature**
**TODO List**:
* admin page
  - [x] Login -> `/login`
  - [x] Logout -> `/logout`
  - [x] Activity list and activity info -> `/activity/list`
  - [x] Activity details -> `/activity/detail`
  - [x] Create activity -> `/activity/create`
  - [x] Update acitivity -> `/activity/detail`
  - [x] Delete activity -> `/activity/delete` 
  - [x] Set up activity menu -> `/activity/menu`
  - [x] Upload image -> `/image/upload`
  - [x] Check ticket -> `/activity/checkin`

* user page
  - [x] Activity Detail -> `/activity/detail`
  - [x] My ticket info -> `/ticket/detail`
  - [x] Validate user -> `/user/bind`
  - [x] Book ticket -> `/ticket/book`
  - [x] Cancel ticket -> `/ticket/cancel`

* wechat
  - [x] Activity list and activity info -> `ListActivityHandler`
  - [x] Activity Detail -> `GetActivityDetailHandler`
  - [x] My ticket info -> `GetTicketHandler`
  - [x] Book ticket-> `BookTicketHandler`
  - [x] Cancel ticket -> `CancelTicketHandler`
  - [x] Sync menu

**Deadline**
2018-10-20

**Additional context**
从THUDM的issue 移动到这儿

**Comment by unbiarirang** [comment]
Done
